### ISSUE TITLE
Can't set enabled to false in initializer (rails)

### ISSUE THREAD

**Issue by patrykwojtynski** [airblade/paper_trail#1038]
I tried to have logging turned on only for specific endpoints in all environments. If you set enabled to false in the initializer it will not work.

In `config/initializers/paper_trail.rb`
```PaperTrail.config.enabled = false```

Then `rails console`
```
[1] pry(main)> PaperTrail.enabled?
=> true
```

After some digging, I found that engine overrides it to true when environment config is missing.

In `PaperTrail::Rails::Engine`
```
initializer "paper_trail.initialisation" do |app|
  PaperTrail.enabled = app.config.paper_trail.fetch(:enabled, true)
end
```

It probably should use `PaperTrail.enabled?` instead of `true`, or even not set `enabled` when config value is missing.

**Comment by jaredbeck** [comment]
Hi Patryk. 

> If you set enabled to false in the initializer it will not work.

Per the docs, that should go in `config/environments`, not initializers. See https://github.com/airblade/paper_trail#2d-turning-papertrail-off

> I tried to have logging turned on only for specific endpoints in all environments.

If that is your goal, try `paper_trail_enabled_for_controller` instead of `PaperTrail.enabled`. See https://github.com/airblade/paper_trail#per-request

**Comment by jaredbeck** [comment]
Hi Patryk, I hope my comments helped. I haven't heard back so I'm going to close this, but please let me know if you find behavior that doesn't match the documentation.
