### ISSUE TITLE
Can Version Associations hold changes as well?

### ISSUE THREAD

**Issue by LKompare** [airblade/paper_trail#1039]
I have a has_and_belong_to_many, which I changed to has many through for version associations.
Ive already captured any changes to main object - say Customers.

However, there are products on the same form and when customers change the selection of those, I need to track those changes as well. 

so products have many customers, customers have many products. i'm tracking changes on customer profile and the products they select.

I see Version Association can be used for reify, but can I alter it to capture the ryou!elation changes so they can be recorded and displayed? 

Thank you!

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
