### ISSUE TITLE
Really no way to do eager loading of versions?

### ISSUE THREAD

**Issue by coreyward** [airblade/paper_trail#222]
I have a collection of objects that I want to inspect at a particular time in the past, e.g.:

```
historical_objects = current_objects.map { |object| object.version_at(date_in_past) }
```

This code is slow due to a lack of “eager loading” (O(n)+1). Is it possible to, without bending paper_trail too far, load versions for a collection from a particular time?

**Comment by mgraham** [comment]
> That's because the `version_at` method uses the `following` scope, which requires an additional query (as it restricts by date). If you wanted you could use Ruby (reduce an additional call to the database) to accomplish the location of the first version after that date while still using the eager association loading like so:
> 
> ```ruby
> Quiz.includes(:versions).first.versions.detect { |q| q.created_at > 30.days.ago }
> ```

This approach is actually very tricky to get correct for a few reasons.  Firstly, the `versions` table does not contain the current state of the model.  Secondly, the first version is typically the `create` version which needs to be excluded.

As near as I can tell, when you call `thing.paper_trail.version_at(date)`:
* if the date is before the `created_at` of the first version, you get `nil`
* if the date is after the `created_at` of the last version, you get the current model

So here's code that takes all that into account (lightly tested):
```
timestamp = DateTime.parse('2023-04-20T04:00:04Z')
records = Quiz.includes(:versions).map do |record|
  result = nil
  if record.updated_at <= timestamp
    result = record
  else
    versions = record.versions.select { |v| v.event == 'update' }.sort_by { |v| v.created_at }.reverse
    if versions.last.created_at <= timestamp
      version = versions.detect { |v| v.created_at <= timestamp }
      result = version.reify if version
    end
  end
  result
end
records.reject! { |record| record.nil? }
```

However, this ends up having a different N+1 problem, because each call to `version.reify` makes another query.
