### ISSUE TITLE
How to extend the Version class

### ISSUE THREAD

**Issue by TvL2386** [airblade/paper_trail#231]
Hi guys,

I want to add a way to create a flexible audit trail for my application.
What I want is to select Version objects based on `created_at` and `item_type`.
Best way to do this imho, is to add a scope to the `Version` class.
I've added the file `app/models/version.rb` and started to extend the `Version` class.

When I have this, I'd like to add more logic in the Version class to built an audit trail.

In development the changes are not picked up on. I wonder why this does not work.
I'm also wondering if I'm trying to do something evil here.

Please help me out!

Kind regards,
Tom

**Comment by joshuapinter** [comment]
FYI, in 2020 as of Version 10 (likely around Version 4+), here's how you extend `PaperTrail::Version` to add some instance methods: 

_`config/initializers/paper_trail.rb`_
```ruby
# Extend PaperTrail::Version with some of our own methods we use.
#
module PaperTrail
  class Version < ApplicationRecord

    include PaperTrail::VersionConcern

    def no_change?
      self.changeset.empty? 
    end

  end
end
```

**Comment by pepetorres1998** [comment]
There is a snippet of code in the docs that misleads to make `PaperTrail::Version` abstract by adding it inside `app/models/paper_trail` instead of `config/initializers/`

https://github.com/paper-trail-gem/paper_trail#configuration

```ruby
# app/models/paper_trail/version.rb
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern
    self.abstract_class = true
  end
end
```

I already forked the gem, is it okay if I send a pull request to change that README.md part of the file?
To actually make it abstract it needs to be on `config/initializers/paper_trail.rb`

```ruby
# config/initializers/paper_trail.rb
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern
    self.abstract_class = true
  end
end
```
