### ISSUE TITLE
Compatibility between paper_trail and composite_primary_keys

### ISSUE THREAD

**Issue by Arkanys** [airblade/paper_trail#320]
Hi,

I'm having some difficulties using paper_trail with tables containing a [composite primary key](https://github.com/composite-primary-keys/composite_primary_keys).

Here's an example to illustrate my problem:

```
class Book
 has_paper_trail
 has_many :books_categories
end

class Category
 has_paper_trail
 has_many :books_categories
end

class BooksCategory
 has_paper_trail
 self.primary_keys = :book_id, :category_id
 belongs_to :book
 belongs_to :category
end
```

BooksCategories doesn't have any `id` field in database and if you call `.id` on an instance of this, you get an array back that looks like that: `[book_id, category_id]`
What happens is that the stored item_id contains only book_id and not the category_id which make this impossible to link the item with its versions.

**Comment by jaredbeck** [comment]
It's been over a year since the last comment here. What's the status of this issue? Is anyone championing it? Was @Arkanys code ever made into a PR?

In my experience, composite foreign keys have never been been popular in ActiveRecord projects, despite being a totally reasonable design decision.

There is a very simple workaround: replace the primary key constraint with a unique constraint, then add a single, conventional `id` column.

Given the simple workaround, which in my experience is very common in ActiveRecord projects, I have no interest in working on this issue in paper_trail, though I'd be happy to help someone else prepare a PR.

**Comment by jaredbeck** [comment]
The current PT schema is incompatible with CPKs, specifically:

- `versions.item_id`, and
- `version_associations.foreign_key_id`

Any thoughts on how to resolve this incompatibility? I think the SQL standard has an array data-type, but it has not been implemented yet by all the RDBMSs we support. Without arrays, I'm not sure how to implement arbitrary-length CPKs.

We do have the [custom version classes][1] feature, which allows models to have their own `versions` table, so maybe we could leverage that, but it's not compatible with association tracking yet, so that would have to be resolved first.

The more I think about this, the harder it sounds.

[1]: https://github.com/airblade/paper_trail#6a-custom-version-classes

**Comment by jaredbeck** [comment]
Given how simple the workaround is, how unconventional CPKs are in rails apps, and how difficult this implementation would be, I think we can close this. If someone wants to champion this in the future, we can re-open.

**Comment by MrQile** [comment]
I believe changing the item_id field to varchar makes CPK work well in storing the composite key in the versions table. I'm currently using 8.1.2 version.

**Comment by contentfree** [comment]
@Quitalizner (almost six years later…) what made the varchar change work here? 

(Also @jaredbeck I believe Composite Primary Keys are officially supported in Rails 7 now, so many years later. Possible to revisit or maybe explicitly call out a workaround in the docs?)
