### ISSUE TITLE
Custom initializer breaks PaperTrail 3.0.3 (rails 3.2)

### ISSUE THREAD

**Issue by flockom** [airblade/paper_trail#392]
3.0.3 seems to be breaking when calling has_paper_trail in a model.
3.0.2 works fine.
top of the stack:

```
undefined method `timestamp_sort_order' for #<Class:0x007fd1d02fad60>
activerecord (3.2.18) lib/active_record/dynamic_matchers.rb:55:in `method_missing'
paper_trail (3.0.3) lib/paper_trail/has_paper_trail.rb:70:in `has_paper_trail'
```

**Comment by drhenner** [comment]
semantic versioning :+1:

**Comment by drhenner** [comment]
NOTE:  In rails 3 I had a Version model inheriting from `ActiveRecord::Base` and it worked but in rails 4 it broke.  I think it should have always broke but make sure you check that your versions table inherits from `PaperTrail::Version`

**Comment by dallas** [comment]
Maybe my case is slightly different, @batter, but your first override (that of adding the `include` into my `Version` class override, works great while adding the `eager_load!` line does not work. I am overriding the base `PaperTrail::Version` class inside of a model file, though, rather than inside of an initializer. Should I be doing it from an initializer instead (for similar `Rails::Engine` reasons)?

**Comment by jaredbeck** [comment]
> I am overriding the base PaperTrail::Version class inside of a model file, though, rather than inside of an initializer.

Dallas, This is the preferred way to extend `PaperTrail::Version` these days. The initializer should only have configuration like `PaperTrail.config.track_associations = false`.
