### ISSUE TITLE
paper_trail_store persists between requests

### ISSUE THREAD

**Issue by grk** [airblade/paper_trail#413]
`paper_trail_store` uses `Thread.current` to store data. This makes the data stored there leak between requests. For example, if one request stores whodunnit, but the next one doesn't, `PaperTrail.whodunnit` still returns the value from the previous request.

A possible fix is to use https://github.com/steveklabnik/request_store instead of `Thread.current`, to have a guarantee that the store will be cleared before each request.

**Comment by rdlugosz** [comment]
+1 on finding a resolution to this, as it leads to rather confusing (and initially very concerning) audit trails. In our case, we're seeing occasional `versions` on the user model for updates to the sign_in timestamps (which, yes, we *do* want to track) where the `whodunnit` field is set to "impossible" user ids (i.e., a user other than the user signing in and not nil).

My first instinct upon seeing this was to assume something nefarious was going on with one of these users. Eventually I realized that this is probably just a bug & landed here. Like others in this thread, we're using Devise and Unicorn and are keeping things pretty vanilla wrt the papertrail config in the models. We're not overriding the methods for setting the whodunnit user.

I'm new to this issue but it seems like @grk's analysis of what's happening is on point. Whatever the fix, the `whodunnit` field should *never* be a value leaked from a previous request—even if that means some additional versions will end up with `nil` values for `whodunnit`.

[also, thanks - PaperTrail has proven to be very useful in our apps!]

**Comment by batter** [comment]
@rdlugosz - Thanks for the follow up, I'm still planning to try to address this soon, however, I don't understand how you would be seeing this issue if you are running a server w/ Unicorn, as Unicorn is **not** multi-threaded and actually says right on the README:

> Does not care if your application is thread-safe or not, workers all run within their own isolated address space and only serve one client at a time for maximum robustness.

Just thought I would point that out to you, since your issue may be different from the one @grk has reported here.

**Comment by grk** [comment]
Even if you're running on a non-multithreaded server, `Thread.current` will persist between requests.

**Comment by TheKidCoder** [comment]
Just saw this happen in a bad way on my app running on Puma. 
Had a massive amount of version marked with impossible whodunnit IDs.
I +1 for using `request_store`

This really needs to be addressed and fixed asap.

**Comment by batter** [comment]
I've been trying to work on swapping in RequestStore instead of Thread.current on a feature branch and for some reason within the controller tests / specs on the dummy app don't seem to be showing the RequestStore object getting cleared like I would expect it to in between requests.  I'll put up a feature branch this afternoon, would you'd be willing to give it a look @grk?

**Comment by mockdeep** [comment]
@batter this is because `RequestStore` acts as a rack middleware, and middleware doesn't get executed in controller specs. You'll have to manually clear it in an `after(:each)`.

**Comment by grk** [comment]
Sure, let me know when you have a feature branch up.

**Comment by batter** [comment]
Thanks @mockdeep for pointing out that middleware doesn't get executed in controller tests and specs, good to know.

Ok @grk, here is the [feature branch I just pushed up](https://github.com/airblade/paper_trail/tree/request_store_integration). I think everything looks good... 

The only concern I have really is with the way `ModelKlass.paper_trail_enabled_for_model?` is implemented in terms of looking into the `PaperTrail.paper_trail_store` object to see if it has been explicitly disabled for an individual model.  This was done to make it thread-safe (see #328 for historical purposes). If you are using the gem in a Rails eco-system, I suppose it doesn't matter, and it probably makes sense for that data to not hold state between requests, but I'm not sure it's the most obvious behavior.  If I call `Widget.paper_trail_off!` I think I would expect `Widget.paper_trail_enabled_for_model?` to continue returning `false` until I explicitly call `Widget.paper_trail_on!`. Thoughts?  Do I need to figure out a different place to store that data now?

**Comment by grk** [comment]
I think there are two cases for calling `paper_trail_off!` we need to consider.

The first one would be calling it during a request. Then, I'd expect this not to persist between requests, otherwise the behavior would be undefined.

Another would be calling it in an initializer - sort of a global switch for the app. I can't think of a good reason to use it like that, but that would be problematic.

I'd change the API to make it more like `without_versioning` and require a block to be given for this method.

**Comment by batter** [comment]
I think we are fine as is because there is already the `PaperTrail.enabled` option for turning things off globally, and then there is already the small scale `without_versioning` method available on model instances which serves that purpose.

Basically I wanted to question whether it made sense to have the ability to turn things off at a model level should persist between requests, but I think the way it was implemented it already wasn't (or at least wasn't supposed to, but perhaps sometimes would do to thread-safety flaws).  Your answer about how you would expect it to behave confirms that the way it works now is fine as it sits currently, unless anyone else has a different opinion and wants to chime in.

**Comment by batter** [comment]
closed by changes in e28d29ef
