### ISSUE TITLE
Suggestion to store 'object_changes' in different table

### ISSUE THREAD

**Issue by ashrafuzzaman** [airblade/paper_trail#421]
Hi guys,
You have done fine job. But I think Audit tools can be more than just to track and view audit data. Audit tools should also allow to be check, who is the first person I have the task assigned to, if I am tracking assigned_to in Task model.

That is possible if we separate the object_changes to separate table, so that later on we can do query on that.

object_changes, should have following data
```                                             
+-----------+----------------+--------+-----------+
| VersionID | Field          | Was    | Now       |
+-------------------------------------------------+
|  XXXXX    | assigned_to_id | 1      | 2         |
+-----------+----------------+--------+-----------+
```

Then we will be able to query on the changes as well.

**Comment by jaredbeck** [comment]
> .. who is the first person I have the task assigned to, if I am tracking assigned_to in Task model.

Another option is to store the `assigned_to_id` in [version metadata][1]. That way, you can efficiently query to find the oldest `assigned_to_id` for a given record.

Given the lack of activity (11 months) and the workarounds mentioned, I'm going to close this issue.  If you are still working on a PR, please let me know.  I'd like to discuss how it could be a plugin instead of going in paper_trail itself.

[1]: https://github.com/airblade/paper_trail#storing-metadata
