### ISSUE TITLE
It would be nice if we could have multiple instances of paper_trail on the same object

### ISSUE THREAD

**Issue by NullVoxPopuli** [airblade/paper_trail#434]
For maybe you want to use two different subclasses of PaperTrail::Version on the same object - like monitoring different attributes or different associations on different lifecycle events.

Right now the references to `self.class.versions_association_name` prevents this ability, as it's a class method.  I suppose there would also need to be a way to determine how each of the methods in has_paper_trail.rb would choose which instance of `versions_association_name` to use.

I'm not sure if it makes sense to even do this -- might be specific to my use case.

idk

**Comment by jaredbeck** [comment]
>>> For maybe you want to use two different subclasses of PaperTrail::Version on the same object - like monitoring different attributes or different associations on different lifecycle events.
>> .. just thinking about the logistics for this type of thing makes my head spin ..
> I'm unsure if there is a way to make it all generic enough to contribute back.

It's an interesting use case.  

Instead of using `has_paper_trail` you could have your own model classes that inherit `PaperTrail::Version`, and write your own AR callbacks that use them directly.

I'd be concerned about adding first-class support for this use case to the API, however.  I expect it would add a lot of complexity to support a very uncommon use case.  Given that concern, and the lack of activity on this, I'm going to close the issue.
