### ISSUE TITLE
When not using new version_associations calling destroy on a version will generate an error

### ISSUE THREAD

**Issue by frenkel** [airblade/paper_trail#465]
I just upgraded an existing project to paper_trail 4.0.0.beta2 and was presented by this error when running my test suite:

    ActiveRecord::StatementInvalid: Could not find table 'version_associations'

I think this is caused by the `dependent: :destroy` in PaperTrail::VersionConcern in the `has_many :version_assosciations`. What would be the best way to work around this? Is it possible to fix this in the concern, or should I just call delete instead?

**Comment by batter** [comment]
Thanks for reporting this! I need to do a better job of testing this feature out extensively on dummy apps outside of the gem test framework to really try and push all possible outcomes.

**Comment by frenkel** [comment]
No problem, we found it before an official release :)

**Comment by emmanne08** [comment]
Hello @batter and @frenkel:

I happened to encounter this issue on PaperTrail 4.0.0.beta3.

I'm using Rails 3.2.21 and Ruby 1.9.3-p551. Initially, I ran `rails generate paper_trail:install` and I opted to use a separate table for my Post model and named it post_versions instead of the default versions. I generated a migration that's similar to the CreateVersions migration wherein I just configured it to use 'post_versions' instead of 'versions'. After running the migrations, I now have the versions and the post_versions table. I generated a model for the PostVersion that I sub-classed from PaperTrail::Version as instructed in the PaperTrail README.md. I didn't forget to set the table name to 'post_versions' for the PostVersion model, I also set `has_paper_trail class_name: 'PostVersion'` within the Post model.

Now when I'm on within the Rails console, I created a Post model and a version of it was automatically created as well. If I call destroy on that created version, I get an error as described below:

    [3] pry(main)> post.versions.last.destroy
      PostVersion Load (0.7ms)  SELECT `post_versions`.* FROM `post_versions` WHERE `post_versions`.`item_id` = 1 AND `post_versions`.`item_type` = 'Post' ORDER BY `post_versions`.`created_at` DESC, `post_versions`.`id` DESC LIMIT 1
       (0.3ms)  BEGIN
       (0.4ms)  ROLLBACK
    ActiveRecord::StatementInvalid: Mysql2::Error: Table 'dummy_2_development.version_associations' doesn't exist: SHOW FULL FIELDS FROM `version_associations`
    from /home/emmanne/.rvm/gems/ruby-1.9.3-p551@dummy_2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'

Even if I declare the PaperTrail::Version to be abstract within an initializer (as described on PaperTrails' README.md), I still get the same error whenever I destroy a version.

Can anyone confirm that this bug is still present on PaperTrail version 4.0.0.beta3?

**Comment by batter** [comment]
@emmanne08 - What commit SHA do you have bundled?

**Comment by emmanne08** [comment]
On my Gemfile.lock, revision is at 6b039a260777291d3fd31b12bd812765927a4cbd.

**Comment by andreydeineko** [comment]
Hi. I have encountered the same issue. Ruby 2.3.0, rails 4.2.5, papertrail 4.0.0. Running 
```ruby
cap staging db:pull
```

I get 
```ruby
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'my_database_development.version_associations' doesn't exist: SHOW FULL FIELDS FROM `version_associations`
```

**Comment by jaredbeck** [comment]
Hi Andrey. This issue is closed. Can you please open a new issue, and provide the information requested in our contributing guide: https://github.com/airblade/paper_trail/blob/master/CONTRIBUTING.md Thanks!
