### ISSUE TITLE
modified has_many query not reified correctly

### ISSUE THREAD

**Issue by theworkerant** [airblade/paper_trail#467]
I have a has_many through association like this:

`has_many :user_things`
`has_many :things, through: :user_things`

This is fine on reification, but I also have an `active` flag on the join model (`user_things`) and another association defined to get those active `thing`s.

`has_many :active_things, -> { where user_things: { active: true } }, through: :user_things, class_name: "Thing", source: :thing`

Upon reification, whatever Rails is doing to retrieve cached queries doesn't activate the `where` on my `active_things` association so I simply get back all `thing`s active `false` and `true`. Ideas?

**Comment by jaredbeck** [comment]
Hi Graham.  Sorry, I know this issue is six months old at this point.  We've had some releases since then, including 4.0.  Can you still reproduce this with 4.0, preferably in a new rails app?

**Comment by jaredbeck** [comment]
Graham, since I haven't heard from you, I'm going to assume you've moved on to a new project, this isn't an issue for you in the latest version, or you just don't have time to respond right now.  If this is still an issue for you, please let us know how to reproduce the problem and we'll be happy to reopen the issue.  Thanks!
