### ISSUE TITLE
Returning versions temporarily as equal value to originator

### ISSUE THREAD

**Issue by rctneil** [airblade/paper_trail#493]
Hello,

Just thought i'd post this here to see if anyone had any ideas on how I could solve the issue posted here: http://community.sitepoint.com/t/papertrail-and-its-versions/113200/4

**Comment by rctneil** [comment]
Just wondering if anyone was able to help with this issue?  I know it's kind of an odd use case but it would be excellent if this was possible.

**Comment by batter** [comment]
Ok took a look through your thread there. Had a couple ideas.

> Unfortunatley I can't use what you posted as I need to be able to chain further query commands onto it in order to sort or limit the returned results

If you wanted to compose a collection of the current version AND the associated versions, you could always put them in a Ruby collection and run ruby sorts and limits.  Depending on how much data you are dealing with this may or may not work for you (probably not for very large data sets).  Ruby has the [`Enumerable#sort`](http://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-sort), [`Enumerable#select`](http://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-select), [`Enumerable#grep`](http://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-grep) and loads of other methods for sorting and limiting / reducing scope for collections that you could probably employ to massage data into sorts you want.

If your data sets are too large and you don't feel that is feasible, you could always look into doing some sort of a mechanism where after every update to a model you are tracking, you have it automatically generate a new version (even though this kind of goes against the idea of the PaperTrail core attitude of "we don't need to store the current version since it already exists on the source model itself", but it would cause all of the data to be in the versions association you're looking for.

Alternatively you could do the sorting and limiting queries you need to against the model's `versions` association and then after doing that just use a couple of conditionals to figure out whether the source model (current version) should be attached to the existing collection you have. This seems like the ideal middle ground IMO since you get the optimization of querying against your database and then only need to use ruby logic to make a few checks at the end to determine if the source model matches the criteria of your collection? (although maybe that doesn't solve the sorting issue..)

Lastly you might consider that perhaps PaperTrail is not the tool for the job.  I'm not an expert but I know there are plenty of [other `ActiveRecord` versioning libraries out there in the Ruby community](https://www.ruby-toolbox.com/categories/Active_Record_Versioning).  And if you can't find one that works to your liking / suits your needs you can always roll your own solution and just manually handle data tracking by storing all the versioned data / old state for models in the same table that can be queried and joined together by matching all of the data sets that apply to the same object to a key of sorts on one of the columns or something like that?

Hope this is helpful, if you have any questions I'm happy to try to answer.  Good luck!

**Comment by rctneil** [comment]
Hey, Thanks for your comments. I'll give each of those some thought.

I'm thinking that building a temporary collection including the normal Model's and Versions may do the trick.

I basically have an index page and want to add a filter that allows a user to include Versions or not. At the moment I have around 1-15 versions so it's not that many and this number will increase very rarely anyway.

I'll have a play around and see what I can come up with. I'll post back my solution here but unsure when that will be as this is only a side project.

**Comment by rctneil** [comment]
@batter Would you please be able to expand on this comment:

"Alternatively you could do the sorting and limiting queries you need to against the model's versions association and then after doing that just use a couple of conditionals to figure out whether the source model (current version) should be attached to the existing collection you have. This seems like the ideal middle ground IMO since you get the optimization of querying against your database and then only need to use ruby logic to make a few checks at the end to determine if the source model matches the criteria of your collection? (although maybe that doesn't solve the sorting issue..)"

I'm not quite sure what you mean?

Thanks
