### ISSUE TITLE
has_many associated record not restored after reify

### ISSUE THREAD

**Issue by mwalsher** [airblade/paper_trail#496]
Great work on the has_many support. It's been a long time coming - glad to see progress here!

I'm experiencing a couple of issues however. Take the following example where an associated record is added, the parent record is reify'd (thus removing the associated record), then the parent record is reify'd again. The associated record should be restored after the second reification but is not.

```
class Post < ActiveRecord::Base
  has_paper_trail
  has_many :comments
end

class Comment < ActiveRecord::Base
  has_paper_trail
  belongs_to :post
end

>> p = Post.create(name: "Test")
>> p.comments.create(text: "Hello")
>> p.versions.last.reify(has_many: true, mark_for_destruction: true).save
# comment is deleted
>> p.reload.versions.last.reify(has_many: true).save
# comment is not restored when it should be
```

**Comment by batter** [comment]
In your example above, this command should fail, like so:

```
>> p.versions.last.reify(has_many: true, mark_for_destruction: true).save
NoMethodError: undefined method `save' for nil:NilClass
```

This is due to the fact that versions for `create` events always return `nil` when `reify` is called upon them since PaperTrail stores the state of what the model looked like *before* the persistence of that state that caused the version to be generated.

**Comment by jaredbeck** [comment]
Closing issue; appears to have been answered.
