### ISSUE TITLE
Is it possible to get object relations "version_at"

### ISSUE THREAD

**Issue by rikkipitt** [airblade/paper_trail#502]
Hi guys,

If I use version_at, what's the best way to pass this along to has_many etc relationships to find them in the state they were in at the time of the parent's state?

```ruby
@book = Book.find(1).version_at(30.minutes.ago).pages
```

E.g. how do I efficiently get pages as they were when Book 1 was 30 minutes ago?

Cheers!

Rikki

**Comment by batter** [comment]
Yes, if you use PaperTrail 4.x (which is unreleased, but available in beta, I recommend you bundle directly from source since that is currently the most stable available), then there is [support for versioning of associations](https://github.com/airblade/paper_trail#associations).

**Comment by rikkipitt** [comment]
Cheers @batter - I'm currently running from source. I'll take a more in depth look and see if I can retrieve the "environment" around a record at a particular time.

**Comment by batter** [comment]
Basically I think you would do something along the lines of this:

```ruby
Book.find(1).version_at(30.minutes.ago).reify(has_many: true).pages
```

You should probably read the README for more details though since I didn't author this feature and am not as familiar with it as I am with the rest of the source code.

**Comment by rikkipitt** [comment]
Thanks for the advice, I'll try and look back and find who created this and copy them in... Your suggestion didn't quite work (version_at returns the Book and not the version). So I did this which still doesn't quite work, the pages don't have the timestamp in the query and thus are the current live versions.

```ruby
# Oddly, has_many here breaks in my case but has_one doesn't...
Book.find(1).version_at(30.minutes.ago).version.reify(has_one: true).pages
```

I might have to do this incrementally and pass the timestamp along to each relation manually.

**Comment by batter** [comment]
@rikkipitt - Apologies, you are correct, I forgot `version_at` returns the actual object instead of the version instance. That being said, [the `version_at` method accepts `reify_options`](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/has_paper_trail.rb#L195), so you can do this:

```ruby
Book.find(1).version_at(30.minutes.ago, has_one: true).pages
```

But yes, in order for the pages to be available you will need to come up with a versioning scheme for them where they have versions persisted at/after the book itself is persisted, which is more complex and an issue I still haven't managed to come up with an automatic solution for.  There is a discussion for a feature that would do this type of thing on #463, contributions are welcome if you manage to come up with a good solution for it, I'd love to see it!
