### ISSUE TITLE
Why does paper_trail store the whole object in each version?

### ISSUE THREAD

**Issue by jmuheim** [airblade/paper_trail#519]
I'm sure this question was asked before and that there are good reasons (performance, simplicity) for having paper_trail store the whole tracked object in each version (instead of only storing the changes like modern versioning systems do).

I'd just like to know these reasons, so please post some links to discussions (if existing, couldn't find any).

I think in theory this could also be done with a custom serializer doing exactly what git does? Couldn't find any attempt to implement one, though.

**Comment by batter** [comment]
There have been some discussions in the past, I'm having difficulty finding them, but it's been this way since it's inception if I'm not mistaken. I believe the rationale is so that you can query for a random / specific version at a specific date and time and be able to grab / restore the attributes it had at that point in time without having to replay / figure out all of the differences it's had since the object's inception.

[Git also stores SnapShots of objects as they are at a certain point in time](http://willi.am/blog/2014/10/14/for-the-last-time-git-stores-snapshots-not-diffs/), so I guess the way PaperTrail stores data is not totally different.

**Comment by jmuheim** [comment]
Thanks for explaining. I had a few more ideas why storing the whole object is a good idea:

- Not every change comes through Rails and paper_trail! If only diffs were stored and somebody changed the record manually (e.g. directly in the DB), the original record couldn't be reified through paper_trail again
- The same for changes to the model (?)
