### ISSUE TITLE
Request: Make have_a_version_with accept a RegEx

### ISSUE THREAD

**Issue by jmuheim** [airblade/paper_trail#520]
I want to check that a field is versioned, but part of the field itself is generated randomly, so I don't have control over that. I'd like to just provide a regular expression to the `have_a_version_with` matcher:

```ruby
    it 'versions name, email, and avatar' do
      user = create :user, :donald, :with_avatar

      expect {
        user.update_attributes! avatar: dummy_file('other_image.jpg')
      }.to change { PaperTrail::Version.count(item_type: 'User') }.by 1

      expect(user).to have_a_version_with avatar: /-image\.jpg$/ # The avatar's name is something like 1428822592-13764-8321-image.jpg
    end
```

**Comment by batter** [comment]
[`have_a_version_with`](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/frameworks/rspec.rb#L28) calls [`PaperTrail::Version#where_object`](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/version_concern.rb#L78), which should return positive matches for partial names just like a Regexp (at least it definitely can if you control the beginning portion of the name as opposed to the end).

I don't believe you can do Regexp matching inside of all SQL databases, thus ActiveRecord doesn't support querying with Regexp's as a value matcher to my knowledge.  Due to that you may be better off querying your versions table with a LIKE query or something to that effect. [This StackOverflow description seems to be more knowledgable of how to accomplish this than I am, so it may help you](http://stackoverflow.com/questions/22799631/postgresql-and-activerecord-where-regex-matching).

It sounds like MySQL and PostgreSQL both have partial support for Regexp matching / querying but they are inconsistent and I don't believe SQLite or other SQL-based databases all support them, thus I don't believe there is an easy way to have a standard accepted Regexp matcher for something like you're asking.

If you or anyone else know more about this than me and I'm wrong I'd love to see a pull request with the code necessary for this.

**Comment by jaredbeck** [comment]
Joshua, as a workaround you could `reify`.  This would be too slow for production code, but it should be fine in a test.

```ruby
expect(user.versions.any? { |v| v.reify.avatar ~ /-image\.jpg$/}).to eq(true)
```

Postgres has support for [regex matching][1] inside a json column.

```sql
select * from versions where object->>'avatar' ~ '-image\.jpg$';
```

However, [arel support for json columns is still being worked on][2].  More importantly, as Ben said, MySQL doesn't have a json type, and [SQLite does not even support regex by default][3].

> .. I'd love to see a pull request with the code necessary for this.

I agree with Ben, I like this feature request, but I'm going to close it for now, and hope that support for this type of query improves in the future.

[1]: http://www.postgresql.org/docs/9.4/static/functions-matching.html
[2]: https://github.com/rails/arel/issues/288
[3]: http://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query
