### ISSUE TITLE
extend with custom scope

### ISSUE THREAD

**Issue by equivalentideas** [airblade/paper_trail#546]
Thanks for the amazing gem ;)

I'm trying the add a new scope to Version to return all the versions from a specific day. I added an initializer paper_trail.rb with:

```
# the following line is required for PaperTrail >= 4.0.0 with Rails
PaperTrail::Rails::Engine.eager_load!

module PaperTrail
  class Version < ActiveRecord::Base
    scope :created_on_date, ->(date) { where("created_at::timestamp::date = ?", date) }
  end
end
```

—but, I'm unable to call this in a view, I get the error 'NoMethodError - undefined method `created_on_date' for #<PaperTrail::Version::ActiveRecord_Relation:0x007fc50048c1b0>'.

This is more a support question than an issue sorry, but is this the right way to extend the Class?

Thanks for your help

**Comment by sergiobayona** [comment]
the ``versions`` method returns an ActiveRecord::AssociationRelation.  So you could just call ``versions`` from a method on the ActiveRecord model that's using PaperTrail. For example:

```
class Widget < ActiveRecord::Base
  has_paper_trail

  def versions_from(date)
    versions.where(created_at: date)
  end
end
```

**Comment by equivalentideas** [comment]
Thanks for that @sergiobayona . I was actually trying to get all versions created on a day, across all the ActiveRecord models using PaperTrail, rather than on an instance of a single model.

**Comment by batter** [comment]
> This is more a support question than an issue sorry, but is this the right way to extend the Class?

Yes... at least I think that should be more or less how it works..

So, I think you would need to define it as a method in current versions of rails instead of declaring a `scope`, since `scope`'s are deprecated (or so I thought).

Also, you may be able to leverage some of the existing scope methods on the `PaperTrail::VersionConcern`, such as [`subsequent`](https://github.com/airblade/paper_trail/blob/v4.0.0.rc1/lib/paper_trail/version_concern.rb#L52), [`preceding`](https://github.com/airblade/paper_trail/blob/v4.0.0.rc1/lib/paper_trail/version_concern.rb#L61), and [`between`](https://github.com/airblade/paper_trail/blob/v4.0.0.rc1/lib/paper_trail/version_concern.rb#L71).  Hope that is helpful, let me know if you still can't manage to get it working and I'll see if I can be of more assistance.

**Comment by batter** [comment]
@equivalentideas - To get all the versions created on a particular day, you could call `PaperTrail::Version.between(date.to_date, date.to_date + 1.day)` or something to that effect. Is that sufficient for your use case until we figure out how to fix custom scope definitions for the `PaperTrail::Version` class? (See the discussion on #492)

**Comment by equivalentideas** [comment]
That does the job, thank @batter .
