### ISSUE TITLE
paper Trail not creating version for update_column

### ISSUE THREAD

**Issue by techverx** [airblade/paper_trail#578]
Hi,
Paper Trail is not creating version for update_column,when i changed update_column to update_attributes it is working fine but i dont want to use update_attributes because of validations, is there any way to create version on update_column?

**Comment by batter** [comment]
This is due to the fact that `update_column(s)` skips not only validations but callbacks. PaperTrail's mechanism for tracking changes are accomplished by hooking into `ActiveRecord` callbacks.

Can you leverage `save(:validate => false)` to skip validations?  Or if you only want to update a single column at a time you could alternatively leverage `update_attribute`.

**Comment by techverx** [comment]
Thanks a lot for quick response, problem resolved
