### ISSUE TITLE
Get all the changes of a attribute for a record.  

### ISSUE THREAD

**Issue by theRealNG** [airblade/paper_trail#597]
I had a use case where I needed to retrieve all the changes that occurred for a particular attribute for a record. I was thinking this was a pretty common use case that people might face.

Shall I go ahead and create a method "trail_for" which does the work or do you have any method which returns the required data?

**Comment by johnnymo87** [comment]
Do you need it to be highly performant, or do you just want a convenience method for debugging?

I only need the latter, so I use this:
```
module Concerns::PaperTrail
  extend ActiveSupport::Concern

  def history_of(attr)
    versions.map(&:reify).compact.map(&attr)
  end
end
```

Here's an incomplete snippet of a spec for this:
```
    it '#history_of' do
      expect(answer.history_of(:text)).to eq []
      answer.update(text: 'my answer')
      expect(answer.history_of(:text)).to eq [nil]
      answer.update(text: '')
      expect(answer.history_of(:text)).to eq [nil, 'my answer']
    end
```

**Comment by batter** [comment]
Unless you are storing the attribute data on your versions table as a metadata column you're not going to have a lot of options in the way of highly performant behavior other than eager loading all of the versions that you have in memory, due to the nature of the way PaperTrail serializes the data prior to inserting into the versions table. You may be able to get improved performance if you are using Postgres and storing your object column as the postgres native `JSON` type then you would have some options to improve the performance via querying most likely.
