### ISSUE TITLE
Potentially missing versions.

### ISSUE THREAD

**Issue by tjohnell-handy** [airblade/paper_trail#608]
Hey guys,

I tried to use google and stackoverflow to find an answer to this question, and came up with nothing.  I'm noticing that my model is missing versions for a particular model.  I know this because I can see that a particular model has a value for an attribute with no corresponding papertrail version showing the change. The model does have an ignore, but it's for an unrelated attribute.

I tried to find in the docs for maybe a warning of instances that a version will not be saved.  Could someone clarify to me instances that a papertrail version might not be created if working directly with an active record?

**Comment by tjohnell-handy** [comment]
So, I just figured out the answer to my own question 10 or so minutes after I made this issue.  Maybe this should have been obvious, but it's because I'm using update_all in portions of the code.

Would this project be opposed  to a small section in the docs "What won't create versions" or something along those lines?

**Comment by batter** [comment]
Any action that skips callbacks will omit version creation as `ActiveRecord` callbacks are used for detecting changes to models. Rather than a doc section to explicitly mention "what won't create versions", since that seems like it could be a long list, it might make more sense to be a little more explicit about declaring that callbacks are used as triggers for detecting changes in the README.  There is a piece of text in the association versioning section that reads:
> Caveats:
> 4. PaperTrail relies on the callbacks on the association model (and the :through association model for Has-Many-Through associations) to record the versions and the relationship between the versions. If the association is changed without invoking the callbacks, Reification won't work...

But I didn't see the word callback used elsewhere in the README. I think it makes sense to mention it in the gem description, at the top of the README.

**Comment by jaredbeck** [comment]
Per Ben's comment, we'll be happy to review a PR that updates the README.  I'll close this issue, thanks.
