### ISSUE TITLE
default_scope causes reify to fail

### ISSUE THREAD

**Issue by hut8** [airblade/paper_trail#671]
Hello! Thanks for `paper_trail`. I'm using it on a project to do auditing and it's working out great except for one issue.

One of my entities has an `is_valid` flag. Almost nowhere do we want instances of this model with `is_valid == false` to be displayed. Therefore it's a good candidate for `default_scope`. When I mark the `is_valid` as true, then update it as false,  `paper_trail` makes the "update" `Version` instance with the `is_valid == true` value just fine.

So let's say I have the `PaperTrail::Version` instance at the penultimate version where `is_valid == true`. Calling `next_version.reify` (without a `default_scope`) gives me the current version in the database. But with a `default_scope`, it gives me `nil`. This is a bug, right? Sorry if I missed it somewhere else; I searched for `default_scope` in the issues and didn't find anything similar. Thanks!

**Comment by jaredbeck** [comment]
Interesting. Because `default_scope` affects all queries, it often has unintended effects like this. So, I try to avoid using `default_scope` in my apps.  

I'd be happy to look into this, though, if you can provide a failing test using our [bug report template](https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb).

Hypothetically, if we were to determine that your default scope was having an effect on reification, I'm not sure what we could do differently.  Other apps may be depending on such an effect.  Let's not get ahead of ourselves though.  Can you provide a failing test?  Thanks!

**Comment by hut8** [comment]
That bug report template is pretty cool. You didn't want that as a PR, right? Here's a gist:

https://gist.github.com/hut8/6db03de7297aa306285d

**Comment by jaredbeck** [comment]
Thanks for the failing test. Let's consider the method in question:

```ruby
def next_version
  subsequent_version = source_version.next
  subsequent_version ? subsequent_version.reify : self.class.find(self.id)
rescue
  nil
end
```

Without your `default_scope`, the query (`self.class.find(self.id)`) produces the following SQL: 

```sql
SELECT  "users".* 
FROM "users" 
WHERE "users"."id" = ? 
LIMIT 1
```

A user is found, `next_version` returns said user, and your test passes.

With your `default_scope`, the `self.class.find(self.id)` produces the following SQL: 

```sql
SELECT  "users".* 
FROM "users" 
WHERE "users"."has_frobulator" = 't' 
  AND "users"."id" = ?
LIMIT 1
```

A `RecordNotFound` error is raised, `next_version` returns `nil`, and your test fails.

Frankly, I find `next_version` to be very confusing. I believe it is designed to reify the subsequent `User` if there is one. If there is not, it queries the "live" `User` record.  I think a more useful method would, if there is no subsequent `User`, return `nil`.  Setting that aside for the moment, if we were to keep the existing design, we could return self instead of performing that query.

```diff
- subsequent_version ? subsequent_version.reify : self.class.find(self.id)
+ subsequent_version ? subsequent_version.reify : self
```

By avoiding the query, your `default_scope` would have no effect.

**Comment by jaredbeck** [comment]
Ben, can you confirm that I understand the intention of the `next_version` method, and possibly comment on my suggested change? Thanks. @batter

**Comment by hut8** [comment]
What about just using `self.class.unscoped.find(self.id)`?

**Comment by hut8** [comment]
Whoops, did not mean to close that.

**Comment by batter** [comment]
@jared, see #200 for background on why it calls `#find` in the case where there is no subsequent version in the stack.  Thinking about it more closely maybe it doesn't always make sense (such as in cases where the current version is a `destroy` event), but that was the idea.  We could call `unscoped` as @hut8 suggests, which isn't a terrible idea.

I honestly don't love `default_scope` usage for exactly this reason but that may just be my opinion / personal preference.

**Comment by jaredbeck** [comment]
> I honestly don't love default_scope usage for exactly this reason but that may just be my opinion / personal preference.

I agree. I never use default_scope in my own applications. My preference here would be to print a warning if a model has `default_scope` and `has_paper_trail`. The warning would say something like "Your model has a default_scope. This will affect database queries performed by PaperTrail, causing PaperTrail to perform differently from how it is documented.  We recommend removing the default_scope.".

> We could call unscoped as @hut8 suggests, which isn't a terrible idea.

If we do that, we should be consistent. We'd have to apply `unscoped` almost anywhere PaperTrail performs a query.  It's possible to imagine an expert user who wants a default_scope and is comfortable with the effects that will have on PaperTrail. Do we want to support that use case? If so, we can't use `unscoped`.

Finally, if we decide to do anything more than print a warning, it'll be a breaking change and would have to wait until PT 5.

**Comment by hut8** [comment]
Now I see why `default_scope` is pretty much always terrible. I agree that this isn't really a bug anymore, it just wasn't what I expected. I'm fine with this being closed.
