### ISSUE TITLE
Tracking :show events

### ISSUE THREAD

**Issue by rgrzeszczuk** [airblade/paper_trail#722]
Is there a plan to support tracking non-lifecycle events?  For example, many regulatory requirements call for tracking access to records.  Currently, setting:

has_paper_trail :on => [:create, :update, :destroy, :show]

results in:

NoMethodError: undefined method `paper_trail_on_show' for Report (call 'Report.connection' to establish a connection):Class

Thanks.

-rg

**Comment by jaredbeck** [comment]
> Is there a plan to support tracking non-lifecycle events? For example, many regulatory requirements call for tracking access to records.

Currently, as you saw, PaperTrail only tracks **writes** to the database (insert, update, delete). PaperTrail is designed around a `versions` table in the database that records these writes. If we were to track **reads** from the database, it wouldn't make sense to do so in the `versions` table. So, tracking reads doesn't really fit PaperTrail's *current* design. I'm not opposed to the idea, but I think it would mean adding another table.  Tracking reads this way introduces a big performance penalty, so I'd want it to be off by default.

Second, I'm not sure how we'd implement this, as there are no AR callbacks for reading. (http://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks) I suppose we could `alias` all methods related to reading, but that is hard to maintain because the AR API will change over time.

Finally, you mentioned "regulatory requirements", and you should be aware that tracking reads in ActiveRecord (or writes) is not guaranteed. PaperTrail, for example, tracks writes with AR callbacks, but it's possible to skip callbacks, or use raw SQL. If you have really strict requirements, you might want to explore tracking at a lower level, even as low as the database itself.

**Comment by rgrzeszczuk** [comment]
Makes sense, thx.

-rg
