### ISSUE TITLE
How save versions before save record?

### ISSUE THREAD

**Issue by carlosalan** [airblade/paper_trail#729]
Guys, 

I need to save versions before save record, any thoughts? 

This is a example that I need save.

```
has_paper_trail :meta => { :object => :prepare_version }

def prepare_version

    {
      object: {
        id: self.id,
        title: self.title
      },
      classrooms: self.classrooms.pluck(:id)
    }

end
```

**Comment by jaredbeck** [comment]
Thanks for your interest in PaperTrail! Our volunteers' time is limited, so we
can only respond on GitHub to bug reports and feature requests. Please ask
*usage questions* on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem)
so that the whole community has a chance to answer your question.

Please use our template
(https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb)
when reporting bugs.

For other questions, please see our contributing guide.
(https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.MD)

Thanks for your contribution!
