### ISSUE TITLE
 is there any way in paper_trail for looking at the data newly updated ?

### ISSUE THREAD

**Issue by FadliKun** [airblade/paper_trail#765]
first, thanks for this usefull plugin.. best regards for the contributors..
i use this paper_ trail plugin in my application, i test the created event, but when i checking the versions table  the object field was null..
 
i want to ask, is there any way in paper_trail for looking at the newly updated data ?

because the version table doesn't have a new/old field... I think the "object" field can record all data changes, "new and old"data, but it's seems not 
"data, but it's seems not.

![paper_trail](https://cloud.githubusercontent.com/assets/14267591/14312604/22453b3a-fc17-11e5-931a-30541ca0a14d.png)

**Comment by jaredbeck** [comment]
Hi FadilKun, thanks for your interest in PaperTrail! Our volunteers' time is limited, so we can only respond on GitHub to bug reports and feature requests. Please ask *usage questions* on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem) so that the whole community has a chance to answer your question.
