### ISSUE TITLE
How to disable associations tracking for a certain model

### ISSUE THREAD

**Issue by westonganger** [airblade/paper_trail#776]
Is it possible to disable the associations tracking for a model?

**Comment by jaredbeck** [comment]
Hi Weston, thanks for your interest in PaperTrail! Our volunteers' time is limited, so we can only respond on GitHub to bug reports and feature requests. Please ask *usage questions* on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem) so that the whole community has a chance to answer your question.

**Comment by wynksaiddestroy** [comment]
As the documentation doesn't mention a way to disable association tracking for certain models, I assume it's not possible right now. So can we turn the question into a feature request and reopen the issue?

**Comment by jaredbeck** [comment]
> As the documentation doesn't mention a way to disable association tracking for certain models, I assume it's not possible right now.

Please see https://github.com/airblade/paper_trail#per-class

**Comment by wynksaiddestroy** [comment]
@jaredbeck: I don't want to turn off PaperTrail as a whole, but only the association tracking on a specific model.

**Comment by jaredbeck** [comment]
> @jaredbeck: I don't want to turn off PaperTrail as a whole, but only the association tracking on a specific model.

I see. I don't think we have such a feature, but I could see it being useful.
