### ISSUE TITLE
Version not saved when using update_attributes - works when using save.

### ISSUE THREAD

**Issue by NielsKSchjoedt** [airblade/paper_trail#796]
I'm having trouble with the paper tails gem.

I have included paper_trail in a few of my models, but I'm having some trouble. When running `model.update_attributes(some_attr: "some val")` nothing gets tracked by paper_trail. However if I do `model.some_attr="some val" ; model.save` then everything works. Any suggestions on how to debug this further?

Rails version: 4.1.14.1
Papertrail version: 4.1.0

**Comment by jaredbeck** [comment]
Hi Niels, thanks for your interest in PaperTrail! Our volunteers' time is limited, so we can only respond on GitHub to bug reports and feature requests. Please ask *usage questions* on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem) so that the whole community has a chance to answer your question.

If you have found a bug, please use our template (https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb) to report it.
