### ISSUE TITLE
People do not realize that the master readme documents unreleased work

### ISSUE THREAD

**Issue by h8rry** [airblade/paper_trail#831]
Just a recommendation.

The default branch should contain a README that's the latest release (ie. 5.1.1), instead of an unreleased version (ie. 5.2.0).

**Comment by jaredbeck** [comment]
Thanks for the suggestion, Harry. You're the second person to ask about this, so I'll try to collect my thoughts here. 

#### The Problem

The problem, as I understand it, is that people go straight to the readme and forgot they are looking at `master`. Some projects add a big warning at the top, e.g. "Hey! These are the docs for `master`". PT is a little calmer, simply giving a list of doc versions.

#### A Strong Convention

It is a strong convention in the ruby community that the default branch (`master`) represents the latest work. I'm not as familiar with other communities, but my impression is that it is the most common git branching model. In fact, on github, pull requests target the default branch unless the requester specifies otherwise. There are other reasons why `master` should represent the latest work, but these conventions are enough.

#### Hosting Docs Separately

PT uses the same git branching model as rspec and rails. However, those big projects host their docs somewhere else. For example, http://guides.rubyonrails.org/ takes you to the latest released docs, currently 4.2.6, but the master branch has docs for 5.1. The rails readme, as a result, is very small, just an introduction. I like this approach, and maybe we can accomplish this with [github pages][1]. My only concern is that it does not add a lot of work to the release process. If someone wants to write a plan for this, I'd be interested.

[1]: https://pages.github.com/

**Comment by jaredbeck** [comment]
> If someone wants to write a plan for this, I'd be interested.

Closing due to lack of interest. If someone wants to take this on, I'd be happy to reopen this.
