### ISSUE TITLE
touch_with_version does not persist version when one version already was persisted

### ISSUE THREAD

**Issue by fsauter** [airblade/paper_trail#888]
Hi together,

I need your help! I'm trying to generate a version for a child manually when the parent is updated using `touch_with_version`. I store the version id of the child as an attribute (belongs_to relation) in the parent model. However this works only the first time. The second time I call `touch_with_version` the version id is incremented, but the version is not persisted to the database (postgres9.6)! If I call touch_with_version 10 times and I inspect the last version object it has the id 10 but only the first one (id=1) is persisted and the total size of versions is always 2. Do you have any hint for me? The code looks like the following in the end:

```ruby
class Parent< ActiveRecord::Base
  after_update :update_child_version, if: :completed?
  # ...
  def update_child_version
      parent.paper_trail.touch_with_version
      # child = belongs_to_relation where the child is a paper_trail model
      # child_version = belongs_to_relation with foreign key to the custom version table for the child model
      self.class.update_all child_version_id: child.versions.last.id
      # This call works the first time, but as soon as a record is persisted only the versions.last.id gets incremented but not persisted so i get a foreign key violation error :-(
  end
  # ...
end
```
Maybe it's helpful, the child model looks somehow like this:
```ruby
class Child < ActiveRecord::Base
  # ...
  class Version < PaperTrail::Version
    self.table_name = :child_versions
    self.sequence_name = :child_versions_id_seq
  end
  # Because I create versions using touch_with_version I ignore all other events
  has_paper_trail on: [], class_name: Child::Version.name
  # ...
end

```
Any thoughts on this?

Greetings from Germany
Florian

**Comment by jaredbeck** [comment]
Per our [contributing guide][1] please ask usage questions on [StackOverflow][2]. 

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub. 

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
