### ISSUE TITLE
Can I opt out of `object_changes` for a particular model or attitribute?

### ISSUE THREAD

**Issue by gkop** [airblade/paper_trail#891]
This is somewhat related to #837 in that I have a large `data` column on my models, however I _think_ I may be better served by the opposite of what's proposed in that issue - that is, to maintain the `object` column but not the `object_changes` column.

We had been running with no `versions.object_changes` column. Now that I've added this column (and gotten the awesome benefits in another table :D thank you folks, this gem is super valuable!), I realized I am writing a lot of data I don't care about for the `data` column in `object_changes` - since a tiny change to `data` causes it to be written out to `versions` effectively 2x.

I don't think skip or ignore is what I want, because I would indeed like the changes to `data` to produce a new version.

Should I go down the custom version model route? Or what do you recommend?

**Comment by jaredbeck** [comment]
> what do you recommend?

Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by gkop** [comment]
Good idea! https://stackoverflow.com/questions/40749467/using-papertrail-can-i-opt-out-of-object-changes-for-a-particular-model-or-at

**Comment by gkop** [comment]
@jaredbeck would you take a look at this question please ^^, and perhaps circulate it among the maintainers? I added a bounty, but it will expire shortly.

<3
