### ISSUE TITLE
remote_syslog stopped suddenly

### ISSUE THREAD

**Issue by Muneer94** [airblade/paper_trail#907]
Thanks for your interest in PaperTrail! Our volunteers' time is limited, so we
can only respond on GitHub to bug reports and feature requests. Please ask
*usage questions* on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem)
so that the whole community has a chance to answer your question.

Please use our template
(https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb)
when reporting bugs.

For other questions, please see our contributing guide.
(https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md)

Thanks for your contribution!

**Comment by Muneer94** [comment]
The remote_syslog process suddenly stopped and I thought we will be getting logs in PaperTrail. When I noticed that we are not getting logs into papertrail for past 9 days. I have checked whether the remote_syslog process is running or not using `service remote_syslog status` it was showing process found  but actually it wasn't running so I have to restart the process. Now I am getting logs but I have to load the logs manually for the last 9 days using `logger -f  <file name>`. Can I know why remote_syslog stopped?

**Comment by jaredbeck** [comment]
Hi Muneer. This sounds like a general question about rails logs, rather than a bug in PT.

Please ask usage questions on StackOverflow (https://stackoverflow.com/tags/paper-trail-gem) so that the whole community has a chance to answer your question.

Please use our template (https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb) when reporting bugs.

**Comment by batter** [comment]
@Muneer94 - Are you sure you're not referring to [papertrail/papertrail-cli](papertrail/papertrail-cli)? The gem for the logging service?
