### ISSUE TITLE
Keep fix version of association

### ISSUE THREAD

**Issue by GCorbel** [airblade/paper_trail#919]
I want to have version of associations at the creation date of a model. It's not very clear so I will give an example : 

```
class User < ActiveRecord::Base
  has_one :coupon
end

class Coupon < ActiveRecord::Base
  has_many :users
end

coupon = Coupon.creat(amount: 100)
user = User.create(coupon: coupon)
user.coupon.amount == 100
coupon.update_attribute('amount', 200)
user.coupon.amount == 200 # I want to have 100
```

This is useful to produce bills or things like that.

I checked the documentation but I didn't find a builtin solution. If there is no solution, I propose to add a `keep_version_of_associations` option on the `has_paper_trail` method. We could also have the possibility to add an array to choose associations with this behavior. Finally, we can also add an option to relationships methods like that `has_one :coupon, keep_same_versions: true`.

What you think ? I'm ready to contribute if you think it's interesting.

**Comment by jaredbeck** [comment]
If I understand your idea correctly, you would like to "freeze" `user` so that persisted changes to its associations are not subsequently visible. This does not seem like a good fit for PaperTrail. PT keeps a record of changes, and allows you to restore those changes. "Freezing" a model's associations seems outside the scope of PT.

Instead, you might try to `reify` at the desired point in time, or you might simply store the necessary `coupon` data in a special-purpose data structure prior to making changes.

**Comment by GCorbel** [comment]
@jaredbeck you understood my needs. I don't know why I did found this solution but I will simply create an `Order` model with an `OrderLine` relation. Very simple and common. Thanks.
