### ISSUE TITLE
create versions for pre existing data

### ISSUE THREAD

**Issue by Fattouh92** [airblade/paper_trail#927]
how should i create versions for data that already exists

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by zealot128** [comment]
FYI I've used a script (data migration) to create a "create" versions for existing records:

```ruby
MyModel.order('id').find_each do |item|    
  next if item.versions.any?
  # papertrail has a method to create the create event
  version = item.paper_trail.record_create

  # .. but that event is missing the changes and whodunnit (or other metadata)
  fake_changes = item.attributes.map { |k, v| [k, [nil, v]] }.to_h
  serialized_object_changes = PaperTrail::Events::Create.new(item, true).
      send(:prepare_object_changes, fake_changes)

   version.update(
      whodunnit: "Data migration",
      object_changes: serialized_object_changes
    )    
end
```
