### ISSUE TITLE
set_paper_trail_whodunnit not working in controllers inherited by ActionController::API

### ISSUE THREAD

**Issue by wonderer007** [airblade/paper_trail#947]
I am using rails 5.1 and trying to add

`before_action :set_paper_trail_whodunnit`

in a API controller which is inherited by **_ActionController::API_** but my changes are not getting tracked for create or update event. I think this is because **_ActionController::API_** is not inherited by  _**ApplicationController**_ how can I make sure it tracks changes with in controllers inherrited by **_ActionController::API_** ?

Thanks

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
