### ISSUE TITLE
whodunnit nil when testing with rspec and devise and capybara

### ISSUE THREAD

**Issue by Kufert** [airblade/paper_trail#986]
Not sure it that's a bug or API change, but we recently upgraded from version 4 to version 7.1.1. 
When rspec browser tests with capybara, the versions are created, but the `whodunnit` is nil. 

When doing the same from the UI, the `whodunnit` is populated as expected with the current user.
When the test begin, we log in the user using devise [`login_as`](https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara), and while using version 4 it used to work as expected, setting the `whodunnit` to the logged in user.
I also tried setting the user in the 'before' step of the test using 
`PaperTrail.whodunnit = user.id  `
but even with that the versions got created with `whodunnit`= nil

What's the proper way to achieve that functionality with version 7.1.1?

**Comment by jaredbeck** [comment]
Hi Yaron, 

Did you upgrade three major versions at once? If so, you probably didn't see the deprecation warning in PT 5 about the `set_paper_trail_whodunnit` callback. Please see https://github.com/airblade/paper_trail/blob/master/doc/warning_about_not_setting_whodunnit.md

In the future, I'd strongly recommend upgrading only one major version at a time; 4 > 5, wait, then 5 > 6, etc. This is general advice for all software.

Per our [contributing guide][1], if you have further usage questions, please ask them on [StackOverflow][2]. Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Kufert** [comment]
@jaredbeck  sorry my bad, needed a feature that was added at v6, and reviewed the release notes, not sure how I missed that. sorry for the trouble and thanks for your time.

**Comment by jaredbeck** [comment]
No worries, glad you're making the upgrade! :+1:
