### ISSUE TITLE
Viewing audit trail in a user friendly manner

### ISSUE THREAD

**Issue by SimonDKnight** [airblade/paper_trail#999]
Hi, So I am currently using paper trail to track all changes in our system and we are displaying it nicely in a table. The problem we are facing is displaying this in a user friendly manner so that a user can navigate it and understand what has happened in our system.

So for example lets say I have a Person model which has one Address model (that belongs to Person). When I create a new Person, I end up with two records in the audit trail (Person and Address). 

How can I group these nicely under the name of Person when it comes to displaying the audit trail? 

How on the audit trail level when I look at both these records do I know that is was the creation of a Person that also caused the creation of an Address?

Now another problem is with update. If I update an Address for a Person, I get 1 record in the audit trail which is Address, but as far as the user is concerned they have actually updated a Person (lets say all the fields are on the same form when they edit a Person).

Again I actually need this to display in the audit trail as a Person being updated (even if at the db level in the versions table its stored as an Address change.

Now the above example is a fairly simple. In our app we have actions that end up with multiple tables being created/updated etc from one form and need to figure out a way to group them nicely for a user. Essentially I need to figure out an easy way to capture the top level model that is being altered.

Does anyone have any ideas or experience that might help here? 

Thanks

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
